# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drtm', '0006_balans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balans',
        ),
    ]
