# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drtm', '0007_delete_balans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
