# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drtm', '0008_balans'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='balans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drtm.Balans'),
        ),
        migrations.AddField(
            model_name='build',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drtm.Service'),
        ),
    ]
